on: [push]

jobs:
  test-nebula-connection:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: test
      uses: rssnyder/nebula-action-step@0.0.10
      env:
        NEBULA_CA_CRT: ${{ secrets.NEBULA_CA_CRT }}
        NEBULA_NODE_CONF: ${{ secrets.NEBULA_NODE_CONF }}
        NEBULA_NODE_CRT: ${{ secrets.NEBULA_NODE_CRT }}
        NEBULA_NODE_KEY: ${{ secrets.NEBULA_NODE_KEY }}
    - shell: bash
      continue-on-error: true
      run: ping 192.168.100.1 -c 5
    - shell: bash
      run: ping 192.168.100.4 -c 5
