on: [push]

jobs:
  test-wg-connection:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: test
      uses: rssnyder/wireguard-action-step@0.0.6
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        hub-hostname: ${{ secrets.HUB_HOSTNAME }}
        public-key: ${{ secrets.PUBLIC_KEY }}
        actions-ip: "10.253.0.6"
        allowed-ips: "10.253.0.6, 10.253.0.15"
    - shell: bash
      run: ping 10.253.0.1 -c 5
    - shell: bash
      run: ping 10.253.0.15 -c 5
